# Generated by Django 3.2 on 2021-05-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/images/')),
                ('posted_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
